services:
  # --- SERVIÇO DO BACKEND ---
  fivelib-api:
    build: 
      context: ./backend      
    container_name: fivelib-api
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    dns:
      - 8.8.8.8
      - 1.1.1.1
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    env_file:
      - ./backend/.env
    environment:
      - WATCHFILES_FORCE_POLLING=true
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    restart: unless-stopped

  # --- SERVIÇO DO FRONTEND ---
  fivelib-frontend:
    build: 
      context: ./frontend
    container_name: fivelib-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app       # Sincroniza o código do front para hot-reload.
      - /app/node_modules     # Protege os node_modules internos do container.
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8001/api/v1
    depends_on:
      - fivelib-api           # Garante que o front só sobe DEPOIS da API.
    restart: unless-stopped