services:
  # --- SERVIÇO DO BACKEND ---
  fivelib-api:
    build: 
      context: ./backend      
    container_name: fivelib-api
    ports:
      - "8001:8001"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    restart: unless-stopped

  # --- SERVIÇO DO FRONTEND ---
  fivelib-frontend:
    build: 
      context: ./frontend
    container_name: fivelib-frontend
    ports:
      - "3000:3000"
      - "5173:5173"         # Porta padrão de React/Next/Vite.
    volumes:
      - ./frontend:/app       # Sincroniza o código do front para hot-reload.
      - /app/node_modules     # Protege os node_modules internos do container.
    environment:
      - VITE_API_URL=http://localhost:8001 # Variável para o front achar a API.
    # depends_on:
    #  - fivelib-api           # Garante que o front só sobe DEPOIS da API.
    restart: unless-stopped